shadowsocks:
  image: shadowsocks/shadowsocks-libev
  ports:
    - "8388:8388/tcp"
    - "8388:8388/udp"
  environment:
    - METHOD=aes-256-gcm
    - DNS_ADDRS=1.1.1.1,1.0.0.1
    - PASSWORD=9MLSpPmNt
    - TZ: Asia/Shanghai
  restart: always
