name: 构建JD Scripts Bot镜像

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - "jd_scripts/Dockerfile.jdbot"
  repository_dispatch:
    types: jd_scripts

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: 构建并推送到Dockerhub镜像仓库
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./jd_scripts/Dockerfile.jdbot
          platforms: linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64
          push: true
          tags: |
            liongoose/jd_scripts_bot:latest
            ghcr.io/${{ steps.repo_name.outputs.lowercase }}/jd_scripts:alpine3.12
